-- this grant is needed in order for app_user to be able to query any functions
-- that are within the private schema. the following SO link contains some
-- useful information about this specific type of problem. to be clear, the
-- problem here as it's currently understood is to allow a specific role
-- (app_user) to be able to execute a function within the private schema.
--
-- https://stackoverflow.com/a/52713519/4028706
--
-- also: https://www.postgresql.org/docs/14/sql-grant.html
--
-- note: the following lines do not work as such, they still result permissions
-- error.
--
-- GRANT EXECUTE ON FUNCTION private.addr_can_be_added(uuid, text) TO app_user;
-- GRANT EXECUTE ON FUNCTION private.addr_can_be_added(text) TO app_user;
--
-- note: for more information on the USAGE privilege, please read this
-- documentation: https://www.postgresql.org/docs/14/ddl-priv.html
GRANT USAGE ON SCHEMA private TO app_user;
