name: registry-server

on:
  pull_request:
  push:
    branches: [master, dev]

jobs:
  lint-and-format:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v4
      - name: nodejs ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: corepack enable
      - run: yarn
      - run: yarn run eslint .

  tests:
    runs-on: ubuntu-latest

    env:
      TEST_DATABASE_URL: postgres://postgres:password@localhost:5432/server
      TEST_DATABASE_USER: postgres
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_BUCKET_REGION: ${{ secrets.AWS_BUCKET_REGION }}
      AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
      GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
      GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
      PASSCODE_MAX_TRY_COUNT: 3
      S3_PROJECTS_PATH: projects-test
      IMAGE_STORAGE_URL: ${{ secrets.IMAGE_STORAGE_URL }}

    strategy:
      matrix:
        node-version: [18.x]

    services:
      postgres:
        image: postgis/postgis:12-master
        env:
          POSTGRES_DB: server
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd "pg_isready -d server -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v4
      - name: nodejs ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: corepack enable
      - run: yarn
      - run: yarn
      - name: 'prepare an empty test database'
        env:
          DATABASE_URL: postgres://postgres:password@localhost:5432/server
          ROOT_DATABASE_URL: postgres://postgres:password@localhost/postgres
        run: yarn run graphile-migrate reset --erase
      - name: 'yarn build' 
        run: yarn build
      - name: 'run tests'
        env:
          MAILERLITE_API_KEY: foobar
          AIRTABLE_API_TOKEN: foobar
          DATABASE_URL: postgres://postgres:password@localhost:5432/server
          CSRF_SECRET: foobar
          CSRF_COOKIE_NAME: __Host-regen-dev.x-csrf-token
        run: yarn serve & yarn test
